/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as invoiceSol from "./Invoice.sol";
export type { invoiceSol };
export type { DummyUSDC } from "./DummyUSDC";
