/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InvoiceInterface extends Interface {
  getFunction(
    nameOrSignature: "createInvoice" | "invoices" | "nextId" | "payInvoice"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invoices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payInvoice",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invoices", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payInvoice", data: BytesLike): Result;
}

export interface Invoice extends BaseContract {
  connect(runner?: ContractRunner | null): Invoice;
  waitForDeployment(): Promise<this>;

  interface: InvoiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createInvoice: TypedContractMethod<
    [
      _payer: AddressLike,
      _payee: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  invoices: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        paid: boolean;
      }
    ],
    "view"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  payInvoice: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createInvoice"
  ): TypedContractMethod<
    [
      _payer: AddressLike,
      _payee: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "invoices"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        paid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payInvoice"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  filters: {};
}
